// 环境变量列表仅在此维护！
const globalAPIParamsList = [
  'PROD_PREFIX',
  'BASE_URL',
  'API_PREFIX_OP',
  'FILE_SERVICE',
  'FILE_VIEW',
  'MAP_SERVICE',
  'TITLE_ONEPIC_MONITOR',
  'TITLE_ONEPIC_WARNING',
  'MAP_CONFIG',
  'DEPLOY_TYPE_CENTRE_CONFIG',
  'TIANDITU_TOKEN',
  'CHANGZHOU_API_PREFIX',
  'CHANGZHOU_APP_ID',
  'CHANGZHOU_APP_SECRET',
  'DEFAULT_AREA_ID',
  'DAHUA_VIDEO_CONFIG',
  'HY_LOGIN_CONFIG',
  'UPLOAD_URL',
  'DEFAULT_USER',
  'LINKAGE_URL',
  'LOGINOUT_URL',
  'SECONDARY',
  'API_PREFIX_LINKAGE_OP',
  'DISPLAY_MODE',
  'LOOP_SECONDS',
  'LIST_SCROOL_STEP_BIG',
  'LIST_SCROOL_STEP_NORMAL'
];

module.exports = { globalAPIParamsList };
