apiVersion: v1
kind: Service
metadata:
  name: web-asset-center
  namespace: {{NAMESPACE}}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
  selector:
    app: web-asset-center
  sessionAffinity: None
  type: ClusterIP
