export enum dictEnum {
  cardType = '101', //证件类型
  vaccinateType = '102', //接种类型
  towNeedle = '03', //两针型
  threeNeedle = '04', //三针型
  towChild = '103', //两针型子类
  threeChild = '104', //三针型子类
  statusType = '105', //状态类型
  confirmType = '106', //确诊类型
  contraindication = '108', //禁忌症
  noReasonType = '109', //未排查到类型
  vaccineCompany = '110', //接种厂商
  taskType = '111', //任务类型
  taskStatus = '112', //任务状态
  vehicleType = '118', //交通类型
  transportStatus = '119', //转运状态
  caseDiscoveryPath = '122', //病例发现途径
  admissionSymptoms = '123', // 入院时症状和体征
  complicationTypes = '124', //  并发症
  imageCharacter = '125', //有无新冠肺炎影像学特征
  specificOccupationTypes = '126', //特定职业人群
  medicalOccupation = '127', //医务人员职位
  smokingType = '128', //吸烟
  medicalHistoryTypes = '129', //既往病史和基本情况
  contacHistory = '130', //接触史
  answer = '131', //是否不
  confirm = '106', //确诊状态
  verifyResult = '135', //核实状态
  categoryModel = '137', //物资规格单位model(小单位)
  categoryUnit = '136', //物资规格单位unit(大单位)
  vaccineInfo = '102', //疫苗接种情况（一针、两针、三针）
  isSpecial = '26002', //是否重点人群
  specialPerson = '26003', //重点人员类型
  cityCardType = '26001', //证件类型
  sampleType = '134', //标本类型
  resultType = '132', //检测结果类型
  trailSource = '140', //轨迹来源
  contactType = '117', //接触方式
  nationality = '215', // 民族
  targetType = '133', //靶标类型
  reportSourceType = '139', //上报来源
  nativeType = '143', //国籍
  risklevelType = '142' //风险等级
}
